### ISSUE TITLE
how to get GoogleNews-vectors-300d.npy

### ISSUE THREAD

**Issue by hfl15** [mcrisc/lexdecomp#2]
I'm a newer in NLP, I want to learn something from your program. I have download the GoogleNews-vectors-negative300.bin, but I down know where I can get the file GoogleNews-vectors-300d.npy, so turn to your help.

**Comment by mcrisc** [comment]
Hi! Please, check the directory `tools`, where you'll find two scripts. Use `word2vec2text.py` to convert the file you downloaded to plain text, then use `text2numpy.py` to get the NumPy array file.
